/**
 * Countries are source directly from the World Bank's list of country codes.
 * For more information, refer to: https://wits.worldbank.org/wits/wits/witshelp/content/codes/country_codes.htm
 */

import { PropertyType } from "@/assets/scripts/PageEditor";

export const LocationRegion = {
    id: "location",
    name: "Location",
    type: PropertyType.Enum,
    options: [
        { value: "ALB", text: "Albania" },
        { value: "DZA", text: "Algeria" },
        { value: "ASM", text: "American Samoa" },
        { value: "AND", text: "Andorra" },
        { value: "AGO", text: "Angola" },
        { value: "AIA", text: "Anguila" },
        { value: "ATG", text: "Antigua and Barbuda" },
        { value: "ARG", text: "Argentina" },
        { value: "ARM", text: "Armenia" },
        { value: "ABW", text: "Aruba" },
        { value: "AUS", text: "Australia" },
        { value: "AUT", text: "Austria" },
        { value: "AZE", text: "Azerbaijan" },
        { value: "BHS", text: "Bahamas, The" },
        { value: "BHR", text: "Bahrain" },
        { value: "BGD", text: "Bangladesh" },
        { value: "BRB", text: "Barbados" },
        { value: "BLR", text: "Belarus" },
        { value: "BEL", text: "Belgium" },
        { value: "BLX", text: "Belgium-Luxembourg" },
        { value: "BLZ", text: "Belize" },
        { value: "BEN", text: "Benin" },
        { value: "BMU", text: "Bermuda" },
        { value: "BTN", text: "Bhutan" },
        { value: "BOL", text: "Bolivia" },
        { value: "BIH", text: "Bosnia and Herzegovina" },
        { value: "BWA", text: "Botswana" },
        { value: "BAT", text: "Br. Antr. Terr" },
        { value: "BRA", text: "Brazil" },
        { value: "IOT", text: "British Indian Ocean Ter." },
        { value: "VGB", text: "British Virgin Islands" },
        { value: "BRN", text: "Brunei" },
        { value: "BGR", text: "Bulgaria" },
        { value: "BFA", text: "Burkina Faso" },
        { value: "BDI", text: "Burundi" },
        { value: "KHM", text: "Cambodia" },
        { value: "CMR", text: "Cameroon" },
        { value: "CAN", text: "Canada" },
        { value: "CPV", text: "Cape Verde" },
        { value: "CYM", text: "Cayman Islands" },
        { value: "CAF", text: "Central African Republic" },
        { value: "TCD", text: "Chad" },
        { value: "CHL", text: "Chile" },
        { value: "CHN", text: "China" },
        { value: "CXR", text: "Christmas Island" },
        { value: "CCK", text: "Cocos (Keeling) Islands" },
        { value: "COL", text: "Colombia" },
        { value: "COM", text: "Comoros" },
        { value: "ZAR", text: "Congo, Dem. Rep." },
        { value: "COG", text: "Congo, Rep." },
        { value: "COK", text: "Cook Islands" },
        { value: "CRI", text: "Costa Rica" },
        { value: "CIV", text: "Cote d'Ivoire" },
        { value: "HRV", text: "Croatia" },
        { value: "CUB", text: "Cuba" },
        { value: "CYP", text: "Cyprus" },
        { value: "CZE", text: "Czech Republic" },
        { value: "CSK", text: "Czechoslovakia" },
        { value: "DNK", text: "Denmark" },
        { value: "DJI", text: "Djibouti" },
        { value: "DMA", text: "Dominica" },
        { value: "DOM", text: "Dominican Republic" },
        { value: "TMP", text: "East Timor" },
        { value: "ECU", text: "Ecuador" },
        { value: "EGY", text: "Egypt, Arab Rep." },
        { value: "SLV", text: "El Salvador" },
        { value: "GNQ", text: "Equatorial Guinea" },
        { value: "ERI", text: "Eritrea" },
        { value: "EST", text: "Estonia" },
        { value: "ETH", text: "Ethiopia (excludes Eritrea)" },
        { value: "ETF", text: "Ethiopia (includes Eritrea)" },
        { value: "EUN", text: "European Union" },
        { value: "FRO", text: "Faeroe Islands" },
        { value: "FLK", text: "Falkland Island" },
        { value: "FJI", text: "Fiji" },
        { value: "FIN", text: "Finland" },
        { value: "PCZ", text: "Fm Panama Cz" },
        { value: "ZW1", text: "Fm Rhod Nyas" },
        { value: "TAN", text: "Fm Tanganyik" },
        { value: "VDR", text: "Fm Vietnam Dr" },
        { value: "SVR", text: "Fm Vietnam Rp" },
        { value: "ZPM", text: "Fm Zanz-Pemb" },
        { value: "ATF", text: "Fr. So. Ant. Tr" },
        { value: "FRA", text: "France" },
        { value: "FRE", text: "Free Zones" },
        { value: "GUF", text: "French Guiana" },
        { value: "PYF", text: "French Polynesia" },
        { value: "GAB", text: "Gabon" },
        { value: "GMB", text: "Gambia, The" },
        { value: "GAZ", text: "Gaza Strip" },
        { value: "GEO", text: "Georgia" },
        { value: "DDR", text: "German Democratic Republic" },
        { value: "DEU", text: "Germany" },
        { value: "GHA", text: "Ghana" },
        { value: "GIB", text: "Gibraltar" },
        { value: "GRC", text: "Greece" },
        { value: "GRL", text: "Greenland" },
        { value: "GRD", text: "Grenada" },
        { value: "GLP", text: "Guadeloupe" },
        { value: "GUM", text: "Guam" },
        { value: "GTM", text: "Guatemala" },
        { value: "GIN", text: "Guinea" },
        { value: "GNB", text: "Guinea-Bissau" },
        { value: "GUY", text: "Guyana" },
        { value: "HTI", text: "Haiti" },
        { value: "VAT", text: "Holy See" },
        { value: "HND", text: "Honduras" },
        { value: "HKG", text: "Hong Kong, China" },
        { value: "HUN", text: "Hungary" },
        { value: "ISL", text: "Iceland" },
        { value: "IND", text: "India" },
        { value: "valueN", text: "Indonesia" },
        { value: "IRN", text: "Iran, Islamic Rep." },
        { value: "IRQ", text: "Iraq" },
        { value: "IRL", text: "Ireland" },
        { value: "ISR", text: "Israel" },
        { value: "ITA", text: "Italy" },
        { value: "JAM", text: "Jamaica" },
        { value: "JPN", text: "Japan" },
        { value: "JTN", text: "Jhonston Island" },
        { value: "JOR", text: "Jordan" },
        { value: "KAZ", text: "Kazakhstan" },
        { value: "KEN", text: "Kenya" },
        { value: "KIR", text: "Kiribati" },
        { value: "PRK", text: "Korea, Dem. Rep." },
        { value: "KOR", text: "Korea, Rep." },
        { value: "KWT", text: "Kuwait" },
        { value: "KGZ", text: "Kyrgyz Republic" },
        { value: "LAO", text: "Lao PDR" },
        { value: "LVA", text: "Latvia" },
        { value: "LBN", text: "Lebanon" },
        { value: "LSO", text: "Lesotho" },
        { value: "LBR", text: "Liberia" },
        { value: "LBY", text: "Libya" },
        { value: "LIE", text: "Liechtenstein" },
        { value: "LTU", text: "Lithuania" },
        { value: "LUX", text: "Luxembourg" },
        { value: "MAC", text: "Macao" },
        { value: "MKD", text: "Macedonia, FYR" },
        { value: "MDG", text: "Madagascar" },
        { value: "MWI", text: "Malawi" },
        { value: "MYS", text: "Malaysia" },
        { value: "MDV", text: "Maldives" },
        { value: "MLI", text: "Mali" },
        { value: "MLT", text: "Malta" },
        { value: "MHL", text: "Marshall Islands" },
        { value: "MTQ", text: "Martinique" },
        { value: "MRT", text: "Mauritania" },
        { value: "MUS", text: "Mauritius" },
        { value: "MEX", text: "Mexico" },
        { value: "FSM", text: "Micronesia, Fed. Sts." },
        { value: "Mvalue", text: "Mvalueway Islands" },
        { value: "MDA", text: "Moldova" },
        { value: "MCO", text: "Monaco" },
        { value: "MNG", text: "Mongolia" },
        { value: "MSR", text: "Montserrat" },
        { value: "MAR", text: "Morocco" },
        { value: "MOZ", text: "Mozambique" },
        { value: "MMR", text: "Myanmar" },
        { value: "NAM", text: "Namibia" },
        { value: "NRU", text: "Nauru" },
        { value: "NPL", text: "Nepal" },
        { value: "NLD", text: "Netherlands" },
        { value: "ANT", text: "Netherlands Antilles" },
        { value: "NZE", text: "Neutral Zone" },
        { value: "NCL", text: "New Caledonia" },
        { value: "NZL", text: "New Zealand" },
        { value: "NIC", text: "Nicaragua" },
        { value: "NER", text: "Niger" },
        { value: "NGA", text: "Nigeria" },
        { value: "NIU", text: "Niue" },
        { value: "NFK", text: "Norfolk Island" },
        { value: "MNP", text: "Northern Mariana Islands" },
        { value: "NOR", text: "Norway" },
        { value: "OMN", text: "Oman" },
        { value: "PCE", text: "Pacific Islands" },
        { value: "PAK", text: "Pakistan" },
        { value: "PLW", text: "Palau" },
        { value: "PAN", text: "Panama" },
        { value: "PNG", text: "Papua New Guinea" },
        { value: "PRY", text: "Paraguay" },
        { value: "PMY", text: "Pen Malaysia" },
        { value: "PER", text: "Peru" },
        { value: "PHL", text: "Philippines" },
        { value: "PCN", text: "Pitcairn" },
        { value: "POL", text: "Poland" },
        { value: "PRT", text: "Portugal" },
        { value: "PRI", text: "Puerto Rico" },
        { value: "QAT", text: "Qatar" },
        { value: "REU", text: "Reunion" },
        { value: "ROM", text: "Romania" },
        { value: "RUS", text: "Russian Federation" },
        { value: "RWA", text: "Rwanda" },
        { value: "RYU", text: "Ryukyu Is" },
        { value: "SBH", text: "Sabah" },
        { value: "SHN", text: "Saint Helena" },
        { value: "KN1", text: "Saint Kitts-Nevis-Anguilla-Aru" },
        { value: "SPM", text: "Saint Pierre and Miquelon" },
        { value: "WSM", text: "Samoa" },
        { value: "SMR", text: "San Marino" },
        { value: "STP", text: "Sao Tome and Principe" },
        { value: "SWK", text: "Sarawak" },
        { value: "SAU", text: "Saudi Arabia" },
        { value: "SEN", text: "Senegal" },
        { value: "SYC", text: "Seychelles" },
        { value: "SLE", text: "Sierra Leone" },
        { value: "SIK", text: "SIKKIM" },
        { value: "SGP", text: "Singapore" },
        { value: "SVK", text: "Slovak Republic" },
        { value: "SVN", text: "Slovenia" },
        { value: "SLB", text: "Solomon Islands" },
        { value: "SOM", text: "Somalia" },
        { value: "ZAF", text: "South Africa" },
        { value: "SVU", text: "Soviet Union" },
        { value: "ESP", text: "Spain" },
        { value: "SPE", text: "Special Categories" },
        { value: "LKA", text: "Sri Lanka" },
        { value: "KNA", text: "St. Kitts and Nevis" },
        { value: "LCA", text: "St. Lucia" },
        { value: "VCT", text: "St. Vincent and the Grenadines" },
        { value: "SDN", text: "Sudan" },
        { value: "SUR", text: "Suriname" },
        { value: "SJM", text: "Svalbard and Jan Mayen Is" },
        { value: "SWZ", text: "Swaziland" },
        { value: "SWE", text: "Sweden" },
        { value: "CHE", text: "Switzerland" },
        { value: "SYR", text: "Syrian Arab Republic" },
        { value: "TWN", text: "Taiwan" },
        { value: "TJK", text: "Tajikistan" },
        { value: "TZA", text: "Tanzania" },
        { value: "THA", text: "Thailand" },
        { value: "TGO", text: "Togo" },
        { value: "TKL", text: "Tokelau" },
        { value: "TON", text: "Tonga" },
        { value: "TTO", text: "Trinvaluead and Tobago" },
        { value: "TUN", text: "Tunisia" },
        { value: "TUR", text: "Turkey" },
        { value: "TKM", text: "Turkmenistan" },
        { value: "TCA", text: "Turks and Caicos Isl." },
        { value: "TUV", text: "Tuvalu" },
        { value: "UGA", text: "Uganda" },
        { value: "UKR", text: "Ukraine" },
        { value: "ARE", text: "United Arab Emirates" },
        { value: "GBR", text: "United Kingdom" },
        { value: "USA", text: "United States" },
        { value: "UNS", text: "Unspecified" },
        { value: "URY", text: "Uruguay" },
        { value: "USP", text: "Us Msc.Pac.I" },
        { value: "UZB", text: "Uzbekistan" },
        { value: "VUT", text: "Vanuatu" },
        { value: "VEN", text: "Venezuela" },
        { value: "VNM", text: "Vietnam" },
        { value: "VIR", text: "Virgin Islands (U.S.)" },
        { value: "WAK", text: "Wake Island" },
        { value: "WLF", text: "Wallis and Futura Isl." },
        { value: "ESH", text: "Western Sahara" },
        { value: "WLD", text: "World" },
        { value: "YDR", text: "Yemen Democratic" },
        { value: "YEM", text: "Yemen, Rep." },
        { value: "SER", text: "Yugoslavia" },
        { value: "YUG", text: "Yugoslavia, FR (Serbia/Montenegro)" },
        { value: "ZMB", text: "Zambia" },
        { value: "ZWE", text: "Zimbabwe" },
        { value: "APAC", text: "Asia Pacific" },
        { value: "Europe", text: "Europe" },
        { value: "Africa", text: "Africa" },
        { value: "MENA", text: "Mvaluedle East North Africa" },
        { value: "SouthA", text: "South America" },
        { value: "NorthA", text: "North America" }
    ]
}
