/**
 * Countries are source directly from the World Bank's list of country codes.
 * For more information, refer to: https://wits.worldbank.org/wits/wits/witshelp/content/codes/country_codes.htm
 */

import { PropertyType } from "@/assets/scripts/AppConfiguration";

export const LocationRegion = {
    id: "location",
    name: "Location",
    type: PropertyType.Enum,
    options: [
        { id: "ALB", text: "Albania", value: "ALB" },
        { id: "DZA", text: "Algeria", value: "DZA" },
        { id: "ASM", text: "American Samoa", value: "ASM" },
        { id: "AND", text: "Andorra", value: "AND" },
        { id: "AGO", text: "Angola", value: "AGO" },
        { id: "AIA", text: "Anguila", value: "AIA" },
        { id: "ATG", text: "Antigua and Barbuda", value: "ATG" },
        { id: "ARG", text: "Argentina", value: "ARG" },
        { id: "ARM", text: "Armenia", value: "ARM" },
        { id: "ABW", text: "Aruba", value: "ABW" },
        { id: "AUS", text: "Australia", value: "AUS" },
        { id: "AUT", text: "Austria", value: "AUT" },
        { id: "AZE", text: "Azerbaijan", value: "AZE" },
        { id: "BHS", text: "Bahamas, The", value: "BHS" },
        { id: "BHR", text: "Bahrain", value: "BHR" },
        { id: "BGD", text: "Bangladesh", value: "BGD" },
        { id: "BRB", text: "Barbados", value: "BRB" },
        { id: "BLR", text: "Belarus", value: "BLR" },
        { id: "BEL", text: "Belgium", value: "BEL" },
        { id: "BLX", text: "Belgium-Luxembourg", value: "BLX" },
        { id: "BLZ", text: "Belize", value: "BLZ" },
        { id: "BEN", text: "Benin", value: "BEN" },
        { id: "BMU", text: "Bermuda", value: "BMU" },
        { id: "BTN", text: "Bhutan", value: "BTN" },
        { id: "BOL", text: "Bolivia", value: "BOL" },
        { id: "BIH", text: "Bosnia and Herzegovina", value: "BIH" },
        { id: "BWA", text: "Botswana", value: "BWA" },
        { id: "BAT", text: "Br. Antr. Terr", value: "BAT" },
        { id: "BRA", text: "Brazil", value: "BRA" },
        { id: "IOT", text: "British Indian Ocean Ter.", value: "IOT" },
        { id: "VGB", text: "British Virgin Islands", value: "VGB" },
        { id: "BRN", text: "Brunei", value: "BRN" },
        { id: "BGR", text: "Bulgaria", value: "BGR" },
        { id: "BFA", text: "Burkina Faso", value: "BFA" },
        { id: "BDI", text: "Burundi", value: "BDI" },
        { id: "KHM", text: "Cambodia", value: "KHM" },
        { id: "CMR", text: "Cameroon", value: "CMR" },
        { id: "CAN", text: "Canada", value: "CAN" },
        { id: "CPV", text: "Cape Verde", value: "CPV" },
        { id: "CYM", text: "Cayman Islands", value: "CYM" },
        { id: "CAF", text: "Central African Republic", value: "CAF" },
        { id: "TCD", text: "Chad", value: "TCD" },
        { id: "CHL", text: "Chile", value: "CHL" },
        { id: "CHN", text: "China", value: "CHN" },
        { id: "CXR", text: "Christmas Island", value: "CXR" },
        { id: "CCK", text: "Cocos (Keeling) Islands", value: "CCK" },
        { id: "COL", text: "Colombia", value: "COL" },
        { id: "COM", text: "Comoros", value: "COM" },
        { id: "ZAR", text: "Congo, Dem. Rep.", value: "ZAR" },
        { id: "COG", text: "Congo, Rep.", value: "COG" },
        { id: "COK", text: "Cook Islands", value: "COK" },
        { id: "CRI", text: "Costa Rica", value: "CRI" },
        { id: "CIV", text: "Cote d'Ivoire", value: "CIV" },
        { id: "HRV", text: "Croatia", value: "HRV" },
        { id: "CUB", text: "Cuba", value: "CUB" },
        { id: "CYP", text: "Cyprus", value: "CYP" },
        { id: "CZE", text: "Czech Republic", value: "CZE" },
        { id: "CSK", text: "Czechoslovakia", value: "CSK" },
        { id: "DNK", text: "Denmark", value: "DNK" },
        { id: "DJI", text: "Djibouti", value: "DJI" },
        { id: "DMA", text: "Dominica", value: "DMA" },
        { id: "DOM", text: "Dominican Republic", value: "DOM" },
        { id: "TMP", text: "East Timor", value: "TMP" },
        { id: "ECU", text: "Ecuador", value: "ECU" },
        { id: "EGY", text: "Egypt, Arab Rep.", value: "EGY" },
        { id: "SLV", text: "El Salvador", value: "SLV" },
        { id: "GNQ", text: "Equatorial Guinea", value: "GNQ" },
        { id: "ERI", text: "Eritrea", value: "ERI" },
        { id: "EST", text: "Estonia", value: "EST" },
        { id: "ETH", text: "Ethiopia (excludes Eritrea)", value: "ETH" },
        { id: "ETF", text: "Ethiopia (includes Eritrea)", value: "ETF" },
        { id: "EUN", text: "European Union", value: "EUN" },
        { id: "FRO", text: "Faeroe Islands", value: "FRO" },
        { id: "FLK", text: "Falkland Island", value: "FLK" },
        { id: "FJI", text: "Fiji", value: "FJI" },
        { id: "FIN", text: "Finland", value: "FIN" },
        { id: "PCZ", text: "Fm Panama Cz", value: "PCZ" },
        { id: "ZW1", text: "Fm Rhod Nyas", value: "ZW1" },
        { id: "TAN", text: "Fm Tanganyik", value: "TAN" },
        { id: "VDR", text: "Fm Vietnam Dr", value: "VDR" },
        { id: "SVR", text: "Fm Vietnam Rp", value: "SVR" },
        { id: "ZPM", text: "Fm Zanz-Pemb", value: "ZPM" },
        { id: "ATF", text: "Fr. So. Ant. Tr", value: "ATF" },
        { id: "FRA", text: "France", value: "FRA" },
        { id: "FRE", text: "Free Zones", value: "FRE" },
        { id: "GUF", text: "French Guiana", value: "GUF" },
        { id: "PYF", text: "French Polynesia", value: "PYF" },
        { id: "GAB", text: "Gabon", value: "GAB" },
        { id: "GMB", text: "Gambia, The", value: "GMB" },
        { id: "GAZ", text: "Gaza Strip", value: "GAZ" },
        { id: "GEO", text: "Georgia", value: "GEO" },
        { id: "DDR", text: "German Democratic Republic", value: "DDR" },
        { id: "DEU", text: "Germany", value: "DEU" },
        { id: "GHA", text: "Ghana", value: "GHA" },
        { id: "GIB", text: "Gibraltar", value: "GIB" },
        { id: "GRC", text: "Greece", value: "GRC" },
        { id: "GRL", text: "Greenland", value: "GRL" },
        { id: "GRD", text: "Grenada", value: "GRD" },
        { id: "GLP", text: "Guadeloupe", value: "GLP" },
        { id: "GUM", text: "Guam", value: "GUM" },
        { id: "GTM", text: "Guatemala", value: "GTM" },
        { id: "GIN", text: "Guinea", value: "GIN" },
        { id: "GNB", text: "Guinea-Bissau", value: "GNB" },
        { id: "GUY", text: "Guyana", value: "GUY" },
        { id: "HTI", text: "Haiti", value: "HTI" },
        { id: "VAT", text: "Holy See", value: "VAT" },
        { id: "HND", text: "Honduras", value: "HND" },
        { id: "HKG", text: "Hong Kong, China", value: "HKG" },
        { id: "HUN", text: "Hungary", value: "HUN" },
        { id: "ISL", text: "Iceland", value: "ISL" },
        { id: "IND", text: "India", value: "IND" },
        { id: "IDN", text: "Indonesia", value: "IDN" },
        { id: "IRN", text: "Iran, Islamic Rep.", value: "IRN" },
        { id: "IRQ", text: "Iraq", value: "IRQ" },
        { id: "IRL", text: "Ireland", value: "IRL" },
        { id: "ISR", text: "Israel", value: "ISR" },
        { id: "ITA", text: "Italy", value: "ITA" },
        { id: "JAM", text: "Jamaica", value: "JAM" },
        { id: "JPN", text: "Japan", value: "JPN" },
        { id: "JTN", text: "Jhonston Island", value: "JTN" },
        { id: "JOR", text: "Jordan", value: "JOR" },
        { id: "KAZ", text: "Kazakhstan", value: "KAZ" },
        { id: "KEN", text: "Kenya", value: "KEN" },
        { id: "KIR", text: "Kiribati", value: "KIR" },
        { id: "PRK", text: "Korea, Dem. Rep.", value: "PRK" },
        { id: "KOR", text: "Korea, Rep.", value: "KOR" },
        { id: "KWT", text: "Kuwait", value: "KWT" },
        { id: "KGZ", text: "Kyrgyz Republic", value: "KGZ" },
        { id: "LAO", text: "Lao PDR", value: "LAO" },
        { id: "LVA", text: "Latvia", value: "LVA" },
        { id: "LBN", text: "Lebanon", value: "LBN" },
        { id: "LSO", text: "Lesotho", value: "LSO" },
        { id: "LBR", text: "Liberia", value: "LBR" },
        { id: "LBY", text: "Libya", value: "LBY" },
        { id: "LIE", text: "Liechtenstein", value: "LIE" },
        { id: "LTU", text: "Lithuania", value: "LTU" },
        { id: "LUX", text: "Luxembourg", value: "LUX" },
        { id: "MAC", text: "Macao", value: "MAC" },
        { id: "MKD", text: "Macedonia, FYR", value: "MKD" },
        { id: "MDG", text: "Madagascar", value: "MDG" },
        { id: "MWI", text: "Malawi", value: "MWI" },
        { id: "MYS", text: "Malaysia", value: "MYS" },
        { id: "MDV", text: "Maldives", value: "MDV" },
        { id: "MLI", text: "Mali", value: "MLI" },
        { id: "MLT", text: "Malta", value: "MLT" },
        { id: "MHL", text: "Marshall Islands", value: "MHL" },
        { id: "MTQ", text: "Martinique", value: "MTQ" },
        { id: "MRT", text: "Mauritania", value: "MRT" },
        { id: "MUS", text: "Mauritius", value: "MUS" },
        { id: "MEX", text: "Mexico", value: "MEX" },
        { id: "FSM", text: "Micronesia, Fed. Sts.", value: "FSM" },
        { id: "MID", text: "Midway Islands", value: "MID" },
        { id: "MDA", text: "Moldova", value: "MDA" },
        { id: "MCO", text: "Monaco", value: "MCO" },
        { id: "MNG", text: "Mongolia", value: "MNG" },
        { id: "MSR", text: "Montserrat", value: "MSR" },
        { id: "MAR", text: "Morocco", value: "MAR" },
        { id: "MOZ", text: "Mozambique", value: "MOZ" },
        { id: "MMR", text: "Myanmar", value: "MMR" },
        { id: "NAM", text: "Namibia", value: "NAM" },
        { id: "NRU", text: "Nauru", value: "NRU" },
        { id: "NPL", text: "Nepal", value: "NPL" },
        { id: "NLD", text: "Netherlands", value: "NLD" },
        { id: "ANT", text: "Netherlands Antilles", value: "ANT" },
        { id: "NZE", text: "Neutral Zone", value: "NZE" },
        { id: "NCL", text: "New Caledonia", value: "NCL" },
        { id: "NZL", text: "New Zealand", value: "NZL" },
        { id: "NIC", text: "Nicaragua", value: "NIC" },
        { id: "NER", text: "Niger", value: "NER" },
        { id: "NGA", text: "Nigeria", value: "NGA" },
        { id: "NIU", text: "Niue", value: "NIU" },
        { id: "NFK", text: "Norfolk Island", value: "NFK" },
        { id: "MNP", text: "Northern Mariana Islands", value: "MNP" },
        { id: "NOR", text: "Norway", value: "NOR" },
        { id: "OMN", text: "Oman", value: "OMN" },
        { id: "PCE", text: "Pacific Islands", value: "PCE" },
        { id: "PAK", text: "Pakistan", value: "PAK" },
        { id: "PLW", text: "Palau", value: "PLW" },
        { id: "PAN", text: "Panama", value: "PAN" },
        { id: "PNG", text: "Papua New Guinea", value: "PNG" },
        { id: "PRY", text: "Paraguay", value: "PRY" },
        { id: "PMY", text: "Pen Malaysia", value: "PMY" },
        { id: "PER", text: "Peru", value: "PER" },
        { id: "PHL", text: "Philippines", value: "PHL" },
        { id: "PCN", text: "Pitcairn", value: "PCN" },
        { id: "POL", text: "Poland", value: "POL" },
        { id: "PRT", text: "Portugal", value: "PRT" },
        { id: "PRI", text: "Puerto Rico", value: "PRI" },
        { id: "QAT", text: "Qatar", value: "QAT" },
        { id: "REU", text: "Reunion", value: "REU" },
        { id: "ROM", text: "Romania", value: "ROM" },
        { id: "RUS", text: "Russian Federation", value: "RUS" },
        { id: "RWA", text: "Rwanda", value: "RWA" },
        { id: "RYU", text: "Ryukyu Is", value: "RYU" },
        { id: "SBH", text: "Sabah", value: "SBH" },
        { id: "SHN", text: "Saint Helena", value: "SHN" },
        { id: "KN1", text: "Saint Kitts-Nevis-Anguilla-Aru", value: "KN1" },
        { id: "SPM", text: "Saint Pierre and Miquelon", value: "SPM" },
        { id: "WSM", text: "Samoa", value: "WSM" },
        { id: "SMR", text: "San Marino", value: "SMR" },
        { id: "STP", text: "Sao Tome and Principe", value: "STP" },
        { id: "SWK", text: "Sarawak", value: "SWK" },
        { id: "SAU", text: "Saudi Arabia", value: "SAU" },
        { id: "SEN", text: "Senegal", value: "SEN" },
        { id: "SYC", text: "Seychelles", value: "SYC" },
        { id: "SLE", text: "Sierra Leone", value: "SLE" },
        { id: "SIK", text: "SIKKIM", value: "SIK" },
        { id: "SGP", text: "Singapore", value: "SGP" },
        { id: "SVK", text: "Slovak Republic", value: "SVK" },
        { id: "SVN", text: "Slovenia", value: "SVN" },
        { id: "SLB", text: "Solomon Islands", value: "SLB" },
        { id: "SOM", text: "Somalia", value: "SOM" },
        { id: "ZAF", text: "South Africa", value: "ZAF" },
        { id: "SVU", text: "Soviet Union", value: "SVU" },
        { id: "ESP", text: "Spain", value: "ESP" },
        { id: "SPE", text: "Special Categories", value: "SPE" },
        { id: "LKA", text: "Sri Lanka", value: "LKA" },
        { id: "KNA", text: "St. Kitts and Nevis", value: "KNA" },
        { id: "LCA", text: "St. Lucia", value: "LCA" },
        { id: "VCT", text: "St. Vincent and the Grenadines", value: "VCT" },
        { id: "SDN", text: "Sudan", value: "SDN" },
        { id: "SUR", text: "Suriname", value: "SUR" },
        { id: "SJM", text: "Svalbard and Jan Mayen Is", value: "SJM" },
        { id: "SWZ", text: "Swaziland", value: "SWZ" },
        { id: "SWE", text: "Sweden", value: "SWE" },
        { id: "CHE", text: "Switzerland", value: "CHE" },
        { id: "SYR", text: "Syrian Arab Republic", value: "SYR" },
        { id: "TWN", text: "Taiwan", value: "TWN" },
        { id: "TJK", text: "Tajikistan", value: "TJK" },
        { id: "TZA", text: "Tanzania", value: "TZA" },
        { id: "THA", text: "Thailand", value: "THA" },
        { id: "TGO", text: "Togo", value: "TGO" },
        { id: "TKL", text: "Tokelau", value: "TKL" },
        { id: "TON", text: "Tonga", value: "TON" },
        { id: "TTO", text: "Trinidad and Tobago", value: "TTO" },
        { id: "TUN", text: "Tunisia", value: "TUN" },
        { id: "TUR", text: "Turkey", value: "TUR" },
        { id: "TKM", text: "Turkmenistan", value: "TKM" },
        { id: "TCA", text: "Turks and Caicos Isl.", value: "TCA" },
        { id: "TUV", text: "Tuvalu", value: "TUV" },
        { id: "UGA", text: "Uganda", value: "UGA" },
        { id: "UKR", text: "Ukraine", value: "UKR" },
        { id: "ARE", text: "United Arab Emirates", value: "ARE" },
        { id: "GBR", text: "United Kingdom", value: "GBR" },
        { id: "USA", text: "United States", value: "USA" },
        { id: "UNS", text: "Unspecified", value: "UNS" },
        { id: "URY", text: "Uruguay", value: "URY" },
        { id: "USP", text: "Us Msc.Pac.I", value: "USP" },
        { id: "UZB", text: "Uzbekistan", value: "UZB" },
        { id: "VUT", text: "Vanuatu", value: "VUT" },
        { id: "VEN", text: "Venezuela", value: "VEN" },
        { id: "VNM", text: "Vietnam", value: "VNM" },
        { id: "VIR", text: "Virgin Islands (U.S.)", value: "VIR" },
        { id: "WAK", text: "Wake Island", value: "WAK" },
        { id: "WLF", text: "Wallis and Futura Isl.", value: "WLF" },
        { id: "ESH", text: "Western Sahara", value: "ESH" },
        { id: "WLD", text: "World", value: "WLD" },
        { id: "YDR", text: "Yemen Democratic", value: "YDR" },
        { id: "YEM", text: "Yemen, Rep.", value: "YEM" },
        { id: "SER", text: "Yugoslavia", value: "SER" },
        { id: "YUG", text: "Yugoslavia, FR (Serbia/Montenegro)", value: "YUG" },
        { id: "ZMB", text: "Zambia", value: "ZMB" },
        { id: "ZWE", text: "Zimbabwe", value: "ZWE" },
        { id: "APAC", text: "Asia Pacific", value: "APAC" },
        { id: "Europe", text: "Europe", value: "Europe" },
        { id: "Africa", text: "Africa", value: "Africa" },
        { id: "MENA", text: "Middle East North Africa", value: "MENA" },
        { id: "SouthA", text: "South America", value: "SouthA" },
        { id: "NorthA", text: "North America", value: "NorthA" }
    ]
}
