/**
 * Sectors are organized by the North American Industry Classification System (NAICS).
 * For more information, refer to: https://www.bls.gov/iag/tgs/iag_index_naics.htm
 */

import { PropertyType } from "@/assets/scripts/PageEditor";

export const Sector = {
    id: "sector",
    name: "Sector",
    type: PropertyType.Enum,
    options: [
        { value: "NAICS 721",   text: "Accommodation " },
        { value: "NAICS 72",    text: "Accommodation and Food Services " },
        { value: "NAICS 561",   text: "Administrative and Support Services " },
        { value: "NAICS 56",    text: "Administrative and Support and Waste Management and Remediation Services " },
        { value: "NAICS 11",    text: "Agriculture, Forestry, Fishing and Hunting " },
        { value: "NAICS 481",   text: "Air Transportation " },
        { value: "NAICS 621",   text: "Ambulatory Health Care Services " },
        { value: "NAICS 713",   text: "Amusement, Gambling, and Recreation Industries " },
        { value: "NAICS 112",   text: "Animal Production " },
        { value: "NAICS 315",   text: "Apparel Manufacturing " },
        { value: "NAICS 71",    text: "Arts, Entertainment, and Recreation " },
        { value: "NAICS 312",   text: "Beverage and Tobacco Product Manufacturing " },
        { value: "NAICS 515",   text: "Broadcasting " },
        { value: "NAICS 444",   text: "Building Material and Garden Equipment and Supplies Dealers " },
        { value: "NAICS 325",   text: "Chemical Manufacturing " },
        { value: "NAICS 448",   text: "Clothing and Clothing Accessories Stores " },
        { value: "NAICS 334",   text: "Computer and Electronic Product Manufacturing " },
        { value: "NAICS 23",    text: "Construction " },
        { value: "NAICS 236",   text: "Construction of Buildings " },
        { value: "NAICS 492",   text: "Couriers and Messengers " },
        { value: "NAICS 522",   text: "Credit Intermediation and Related Activities " },
        { value: "NAICS 111",   text: "Crop Production " },
        { value: "NAICS 518",   text: "Data Processing, Hosting, and Related Services " },
        { value: "NAICS 61",    text: "Educational Services " },
        { value: "NAICS 335",   text: "Electrical Equipment, Appliance, and Component Manufacturing " },
        { value: "NAICS 443",   text: "Electronics and Appliance Stores " },
        { value: "NAICS 332",   text: "Fabricated Metal Product Manufacturing " },
        { value: "NAICS 52",    text: "Finance and Insurance " },
        { value: "NAICS 114",   text: "Fishing, Hunting and Trapping " },
        { value: "NAICS 311",   text: "Food Manufacturing " },
        { value: "NAICS 722",   text: "Food Services and Drinking Places " },
        { value: "NAICS 445",   text: "Food and Beverage Stores " },
        { value: "NAICS 113",   text: "Forestry and Logging " },
        { value: "NAICS 525",   text: "Funds, Trusts, and Other Financial Vehicles " },
        { value: "NAICS 442",   text: "Furniture and Home Furnishings Stores " },
        { value: "NAICS 447",   text: "Gasoline Stations " },
        { value: "NAICS 452",   text: "General Merchandise Stores " },
        { value: "NAICS 62",    text: "Health Care and Social Assistance " },
        { value: "NAICS 446",   text: "Health and Personal Care Stores " },
        { value: "NAICS 237",   text: "Heavy and Civil Engineering Construction " },
        { value: "NAICS 622",   text: "Hospitals " },
        { value: "NAICS 51",    text: "Information " },
        { value: "NAICS 524",   text: "Insurance Carriers and Related Activities " },
        { value: "NAICS 516",   text: "Internet Publishing and Broadcasting " },
        { value: "NAICS 316",   text: "Leather and Allied Product Manufacturing " },
        { value: "NAICS 533",   text: "Lessors of Nonfinancial Intangible Assets " },
        { value: "NAICS 333",   text: "Machinery Manufacturing " },
        { value: "NAICS 55",    text: "Management of Companies and Enterprises " },
        { value: "NAICS 31-33", text: "Manufacturing " },
        { value: "NAICS 423",   text: "Merchant Wholesalers, Durable Goods " },
        { value: "NAICS 424",   text: "Merchant Wholesalers, Nondurable Goods " },
        { value: "NAICS 212",   text: "Mining " },
        { value: "NAICS 21",    text: "Mining, Quarrying, and Oil and Gas Extraction " },
        { value: "NAICS 339",   text: "Miscellaneous Manufacturing " },
        { value: "NAICS 453",   text: "Miscellaneous Store Retailers " },
        { value: "NAICS 521",   text: "Monetary Authorities - Central Bank " },
        { value: "NAICS 512",   text: "Motion Picture and Sound Recording Industries " },
        { value: "NAICS 441",   text: "Motor Vehicle and Parts Dealers " },
        { value: "NAICS 712",   text: "Museums, Historical Sites, and Similar Institutions " },
        { value: "NAICS 327",   text: "Nonmetallic Mineral Product Manufacturing " },
        { value: "NAICS 454",   text: "Nonstore Retailers " },
        { value: "NAICS 623",   text: "Nursing and Residential Care Facilities " },
        { value: "NAICS 211",   text: "Oil and Gas Extraction " },
        { value: "NAICS 519",   text: "Other Information Services " },
        { value: "NAICS 81",    text: "Other Services " },
        { value: "NAICS 322",   text: "Paper Manufacturing " },
        { value: "NAICS 711",   text: "Performing Arts, Spectator Sports, and Related Industries " },
        { value: "NAICS 812",   text: "Personal and Laundry Services " },
        { value: "NAICS 324",   text: "Petroleum and Coal Products Manufacturing " },
        { value: "NAICS 486",   text: "Pipeline Transportation " },
        { value: "NAICS 326",   text: "Plastics and Rubber Products Manufacturing " },
        { value: "NAICS 491",   text: "Postal Service " },
        { value: "NAICS 331",   text: "Primary Metal Manufacturing " },
        { value: "NAICS 323",   text: "Printing and Related Support Activities " },
        { value: "NAICS 814",   text: "Private Households " },
        { value: "NAICS 54",    text: "Professional, Scientific, and Technical Services " },
        { value: "NAICS 511",   text: "Publishing Industries " },
        { value: "NAICS 482",   text: "Rail Transportation " },
        { value: "NAICS 531",   text: "Real Estate " },
        { value: "NAICS 53",    text: "Real Estate and Rental and Leasing " },
        { value: "NAICS 813",   text: "Religious, Grantmaking, Civic, Professional, and Similar Organizations " },
        { value: "NAICS 532",   text: "Rental and Leasing Services " },
        { value: "NAICS 811",   text: "Repair and Maintenance " },
        { value: "NAICS 44-45", text: "Retail Trade " },
        { value: "NAICS 487",   text: "Scenic and Sightseeing Transportation " },
        { value: "NAICS 523",   text: "Securities, Commodity Contracts, and Other Financial Investments and Related Activities " },
        { value: "NAICS 624",   text: "Social Assistance " },
        { value: "NAICS 238",   text: "Specialty Trade Contractors " },
        { value: "NAICS 451",   text: "Sporting Goods, Hobby, Book, and Music Stores " },
        { value: "NAICS 115",   text: "Support Activities for Agriculture and Forestry " },
        { value: "NAICS 213",   text: "Support Activities for Mining " },
        { value: "NAICS 488",   text: "Support Activities for Transportation " },
        { value: "NAICS 517",   text: "Telecommunications " },
        { value: "NAICS 313",   text: "Textile Mills " },
        { value: "NAICS 314",   text: "Textile Product Mills " },
        { value: "NAICS 485",   text: "Transit and Ground Passenger Transportation " },
        { value: "NAICS 336",   text: "Transportation Equipment Manufacturing " },
        { value: "NAICS 48-49", text: "Transportation and Warehousing " },
        { value: "NAICS 484",   text: "Truck Transportation " },
        { value: "NAICS 22",    text: "Utilities " },
        { value: "NAICS 493",   text: "Warehousing and Storage " },
        { value: "NAICS 562",   text: "Waste Management and Remediation Services " },
        { value: "NAICS 483",   text: "Water Transportation " },
        { value: "NAICS 425",   text: "Wholesale Electronic Markets and Agents and Brokers " },
        { value: "NAICS 42",    text: "Wholesale Trade " },
        { value: "NAICS 321",   text: "Wood Product Manufacturing " }
    ]
}
